### ISSUE TITLE
Don't work option APPLICATION_DATABASE=sample

### ISSUE THREAD

**Issue by olegspk** [vepo/mongo#1]
Hi,
I create your file docker-compose.yml:
version '3'
services:
  db:
    image: vepo/mongo
    environment:
      - AUTH=yes
      - ADMIN_USER=admin
      - ADMIN_PASS=admin123
      - APPLICATION_DATABASE=sample
      - APPLICATION_USER=aashrey
      - APPLICATION_PASS=admin123
    ports:
      - "27017:27017"

But, can't connect to this db: sample. Have a authentificate error with: aashrey/admin123 and admin/admin123
Can access only db: admin
What's problem ? Parameter APPLICATION_DATABASE don't work?

**Comment by vepo** [comment]
Yes! There was a problem with some roles! It has change from mongo versions.

I had fixed and create a sample using your password and username: https://github.com/vepo/mongo-client
